### ISSUE TITLE
Change word break

### ISSUE THREAD

**Issue by PxlBuzzard** [craigcabrey/ratemycoop#154]
All of the markdown-based content is currently using `word-break: break-all;`. However, that results in harder to read review descriptions (as an example):

Current:

![wordwrap-current](https://cloud.githubusercontent.com/assets/512416/6681840/2f96a458-cc2b-11e4-9613-8ddf3ae01e38.PNG)

Proposed:

![wordwrap-after](https://cloud.githubusercontent.com/assets/512416/6681841/2fad30a6-cc2b-11e4-9a59-bc8dd019e915.PNG)

The primary offending CSS is in `.markdown-preview`, though there might be other places to override.

**Comment by kocsenc** [comment]
Fixed in hotfix in `develop` branch. Thanks @PxlBuzzard
