### ISSUE TITLE
Use a default image if the image doesnt work

### ISSUE THREAD

**Issue by skuloth** [craigcabrey/ratemycoop#161]
On company pages if the image does not load, you should load a default image.

**Comment by kocsenc** [comment]
@skuloth , do you mind sharing with us which company this happened for you? When testing [this company](https://ratemycoop.io/#/company/MAC%20Source%20Communications),  a default building icon shows.

Can you not see the icon?

**Comment by craigcabrey** [comment]
He was talking about when you add a company with a user supplied URL. If the supplied URL is invalid, the browser shows a broken link image on the company page instead of our default 'building' icon.

**Comment by kocsenc** [comment]
How are we going to check if it's a valid url for an icon?
