### ISSUE TITLE
Verify Email Link

### ISSUE THREAD

**Issue by veracus** [craigcabrey/ratemycoop#167]
Verify email links you to 127.0.0.1 address.

Example from email:
https://127.0.0.1/api/v1/Users/confirm?uid=176&redirect=/&token=x

**Comment by craigcabrey** [comment]
Huh, I thought we fixed that. I'll look into it.

**Comment by kocsenc** [comment]
@craigcabrey any news on this one?

**Comment by bbesmanoff** [comment]
Still seems to be a problem.

**Comment by computermatt** [comment]
+1

**Comment by kocsenc** [comment]
We will be linking existing RMC accounts to RIT accounts, so this won't even be a problem anymore. Closing and see #11 for follow-up

**Comment by jamesa** [comment]
@kocsenc so future versions of RMC won't have email validation, then, because it'll go off RIT's auth?

**Comment by kocsenc** [comment]
@jamesa correct.

**Comment by jcdesimp** [comment]
Technically still a problem see PR #181
