### ISSUE TITLE
Top bar search box doesn't work

### ISSUE THREAD

**Issue by thenaterhood** [craigcabrey/ratemycoop#168]
As the title says. The search box in the top bar when you're viewing a company seems to be non-functional, at least for me. It used to work, just happened to run into that today.

Chromium 41.0.2272.101, Arch Linux.

**Comment by jcdesimp** [comment]
Can you confirm that you had internet connectivity at the time of the issue?

**Comment by thenaterhood** [comment]
I did since I was also messaging people, visited the site to look at something. Problem hung around through a couple of refreshes.

Seems to be alright now though, so I can't say too much. Chromium could have been being a little temperamental.

**Comment by jcdesimp** [comment]
@thenaterhood ok we'll close for now, report back if the issue seems to be recurring.
