### ISSUE TITLE
Not Authorized User - even after registration and submissions

### ISSUE THREAD

**Issue by sarawr29** [craigcabrey/ratemycoop#171]
I registered to access the system a couple of weeks ago. I entered my reviews for a few companies and logged out.
Today, I know I have the correct password and username (stored in LastPass) and have not changed my RIT password. System will not allow me access and says my credentials are invalid.

**Comment by sarawr29** [comment]
Should have an error message to indicate proper formatting of username to include @rit.edu

**Comment by kocsenc** [comment]
Thans @sarawr29 , We'll check it right up. This is  probably a good incentive for a 'reset password' feature.
