### ISSUE TITLE
Search results do not display recently added company

### ISSUE THREAD

**Issue by dkgramming** [craigcabrey/ratemycoop#176]
I recently added this company page (https://ratemycoop.io/#/company/Blue%20Apron). I can only access it by manually entering the URL.
![screen shot 2015-08-11 at 1 07 19 am](https://cloud.githubusercontent.com/assets/6193072/9190634/5fdb2a7c-3fc5-11e5-8de4-78b4aaaa3b6d.png)

The search doesn't display it as a result though:
![screen shot 2015-08-11 at 1 05 44 am](https://cloud.githubusercontent.com/assets/6193072/9190606/354e12f6-3fc5-11e5-9d4b-2c653c8fe71e.png)

**Comment by craigcabrey** [comment]
This is actually expected behavior. Companies added by users will not show up until approved. I'm beginning the implementation of a new backend shortly, so we might revisit how this works.

**Comment by craigcabrey** [comment]
All pending companies reviewed and approved.
