### ISSUE TITLE
E-mail verification link points to 127.0.0.1

### ISSUE THREAD

**Issue by zmyaro** [craigcabrey/ratemycoop#177]
The e-mail verification link points to https://127.0.0.1/api/v1/Users/confirm?uid={uid}&redirect=/&token={token} instead of the domain of the instance (ratemycoop.io, for the live version).

**Comment by TLMcNulty** [comment]
Duplicate of this issue.

**Comment by liam-middlebrook** [comment]
Duplicate of #167

**Comment by kocsenc** [comment]
We've been trying to fix this the right way; but it seems we'll have to hardcode the api root to the email.

**Comment by jcdesimp** [comment]
@kocsenc the PR is waiting #182

**Comment by jcdesimp** [comment]
fixed in #182

**Comment by msoucy** [comment]
That doesn't quite seem like it actually fixes the issue, just hardcodes it even more.
