### ISSUE TITLE
Cannot create new company

### ISSUE THREAD

**Issue by bigshebang** [craigcabrey/ratemycoop#180]
I've been trying to create a company but it doesn't seem to be working right now. I get the message "It seems something went wrong!" but that's it. I tried including information in every text box and then only the boxes with a red asterisk.

**Comment by craigcabrey** [comment]
Would you mind telling us the name of the company you were trying to add? If you don't want it here publicly, feel free to email me.

**Comment by kocsenc** [comment]
Stale; closing
