### ISSUE TITLE
Search should ignore trailing whitespace characters

### ISSUE THREAD

**Issue by jcdesimp** [craigcabrey/ratemycoop#80]
If a search query ends in a space, for example "Xerox " then expected results are not returned. This query should resolve to "xerox" but it does not. This condition can occur what using type suggestions on mobile devices where a space is automatically added at the end. 

This issue should be solvable by ignoring trailing whitespace characters when resolving search queries.

**Comment by kocsenc** [comment]
Fixed with enter to search fix
